# Generated by Django 3.2.6 on 2021-08-31 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_alter_page_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 31, 11, 46, 15, 983147)),
        ),
    ]
